version: '3.8'

services:
  backend:
    container_name: median_link
    env_file:
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always

  backend:
    container_name: median_mesh
    env_file:
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    restart: always
