version: '3.8'

services:
  median_link:
    container_name: median_link
    env_file:
      - .env
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /etc/letsencrypt/archive/dullbox.ru/:/app/cert/
    ports:
      - 8888:8888
    restart: always
